### ISSUE TITLE
[BUG][ReadAllMails] Error al leer correos con Senders que contienen comillas

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#132]
**Describe the bug**
Se reciben correos de proveedores y si el sender contiene comillas ocasiona que el proceso se detenga

**To Reproduce**
Enviar un correo con el sender o el nombre del anexo entre comillas 

**Log**
Sender:
`2021-03-21T14:01:41.6206587Z 21/03/2021 8:01:07 - LoadJSON object "{ "MailID" : "AAMkAGVmMmJhZDA3LTI2NDItNDUyMC04NTMzLWJjYzJmMjI0N2YyYQBGAAAAAABCmQKvIsvARbBk6ZtnDkkgBwBSvHv6xUN3RrdRHLsWJ9uvAAAAAAEMAABSvHv6xUN3RrdRHLsWJ9uvAAA4aa9sAAA=" , "MailDate" : "17/03/2021 12:21:27" , "MailSender" : ""System Administrator"@myexchangeemail.com" , "MailAttachment": [] }" : Running
2021-03-21T14:01:41.6207515Z 21/03/2021 8:01:07 - Error, invalid JSON
2021-03-21T14:01:41.6208402Z 21/03/2021 8:01:07 - Error : After parsing a value an unexpected character was encountered: S. Path 'MailSender', line 1, position 224.
2021-03-21T14:01:41.6210557Z 21/03/2021 8:01:07 -    at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
2021-03-21T14:01:41.6211808Z    at Newtonsoft.Json.JsonTextReader.Read()
2021-03-21T14:01:41.6213306Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
2021-03-21T14:01:41.6214915Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2021-03-21T14:01:41.6216324Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2021-03-21T14:01:41.6217328Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2021-03-21T14:01:41.6218625Z    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2021-03-21T14:01:41.6220178Z    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2021-03-21T14:01:41.6220930Z    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2021-03-21T14:01:41.6222255Z    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
2021-03-21T14:01:41.6223445Z    at MixedReader.MixedExecute.LoadJSON(String action) in C:\Users\erlik.corona\Source\Repos\AutomationPlatform\MixedReader\MixedExecute.cs:line 10436
2021-03-21T14:01:41.6225661Z 21/03/2021 8:01:07 - LoadJSON object "{ "MailID" : "AAMkAGVmMmJhZDA3LTI2NDItNDUyMC04NTMzLWJjYzJmMjI0N2YyYQBGAAAAAABCmQKvIsvARbBk6ZtnDkkgBwBSvHv6xUN3RrdRHLsWJ9uvAAAAAAEMAABSvHv6xUN3RrdRHLsWJ9uvAAA4aa9sAAA=" , "MailDate" : "17/03/2021 12:21:27" , "MailSender" : ""System Administrator"@myexchangeemail.com" , "MailAttachment": [] }" : Error`

**Expected behavior**
Eliminar las comillas para no meter ruido a la sintaxis del código y que se pueda seguir procesando la información.

**Screenshots**
![image](https://user-images.githubusercontent.com/54807268/112073356-8e327400-8b39-11eb-8260-543de23cd2ed.png)

**Desktop (please complete the following information):**
Process ID: 9870119
Turing Version: 20210310T0032

**Additional context**
https://frida-admin.web.app/Documentation/Readers/Outlook%20Reader/ReadAllMails

**Comment by FaustinoLechuga** [comment]
Se creo una una versión que resuelve el problema, cuando la puedas probar indícamelo en este ticket para poder mandarte la versión. Ademas, me podrias compartir el log de la ejecucion que presento el error para analizarlo mas a detalle y verificar que no se omitio nada.

**Comment by rubenleal** [comment]
Gracias Tino, mándame la versión por favor.

Comparto log completo con el detalle:
[logCorreosComillas.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6212365/logCorreosComillas.txt)

**Comment by FaustinoLechuga** [comment]
Listo, ya te lo mande. Cuando realices las pruebas me avisas que tal funciona.

**Comment by gantonioid** [comment]
@FaustinoLechuga @rubenleal cómo va este tema?

**Comment by rubenleal** [comment]
Funcionó, muchas gracias. 
[logSenderComillas.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6259285/logSenderComillas.txt)
