### ISSUE TITLE
error al abrir workbooks que no son xlsx[BUG][Excel/Browpet/Titanium]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#170]
**Describe the bug**
Al intentar abrir un csv o xls marca  error 

**To Reproduce**
Intentar abrir un csv o xls

**Bug information**
```
Excel LoadWBook "C:\Users\eva\Downloads\Reporte_Comprador_510_FARMACIA_20211027.xls" as bookFARMACIA : Running
10/27/2021 12:48:05 PM - The Workbook is protected and could not be opened.
10/27/2021 12:48:05 PM - Excel LoadWBook "C:\Users\eva\Downloads\Reporte_Comprador_510_FARMACIA_20211027.xls" as bookFARMACIA : Error
Exception Type : 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
Exception Message : 
Cannot convert type 'string' to 'bool'
Exception StackTrace : 
   at CallSite.Target(Closure , CallSite , Object )
   at SharedModels.Helpers.ErrorHelper.CommitLog(Int32 _procID, String RunID, Boolean append) in C:\Users\erlik.corona\Source\Repos\AutomationPlatform\SharedModels\Helpers\ErrorHelper.cs:line 89
10/27/2021 12:48:05 PM - Dispose failed, killing Excel.exe
10/27/2021 12:48:06 PM - Execution ended
Exception Type : 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
Exception Message : 
Cannot convert type 'string' to 'bool'
Exception StackTrace : 
   at CallSite.Target(Closure , CallSite , Object )
   at SharedModels.Helpers.ErrorHelper.CommitLog(Int32 _procID, String RunID, Boolean append) in C:\Users\erlik.corona\Source\Repos\AutomationPlatform\SharedModels\Helpers\ErrorHelper.cs:line 89
```

**Expected behavior**
abrir el xls

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - Version de Turing 20211020T1544

**Additional context**
Máquina física

**Comment by jorgergarciaf** [comment]
Se asignó versión, siendo exitosas las pruebas y funcionamiento. Se cierra ticket
