### ISSUE TITLE
El comando Drag and Drop arroja error

### ISSUE THREAD

**Issue by julio-soto-0517** [FridaSupport/CognitiveTestingMX#25]
Al ejecutar un script con el comando DragAndDrop para arrastrar una imagen, se cierra la ejecución y el log muestra el siguiente error: 

**System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.WindowsAzure.Storage.File.CloudFile.DownloadToFile(String path, FileMode mode, AccessCondition accessCondition, FileRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\File\CloudFile.cs:line 540
   at AzureStorage.AzureBot.Download(String fileName, String processId, String userEmail, String runProcessId, String pathOptional) in C:\Users\andres.cruz\source\repos\AutomationPlatform\AzureStorage\AzureBot.cs:line 498
   at TitaniumReader.TitaniumExecute.DragAndDrop(String action) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 357
   at TitaniumReader.TitaniumExecute.SelectAction(String action, Dictionary`2 variables) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 276
   at TitaniumReader.TitaniumExecute.RunLine(String paso, Dictionary`2 variables) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 125**

Turing Version: 20190812T1159

**Comment by gantonioid** [comment]
Puedes poner tu línea del script que arroja esta falla y log más completo por favor?

**Comment by julio-soto-0517** [comment]
Log:
9/19/2019 2:42:38 PM -  : Success
9/19/2019 2:42:38 PM - #Agregar productos a lista de más vendidos: Running
9/19/2019 2:42:38 PM - Agregar productos a lista de más vendidos : Success
9/19/2019 2:42:38 PM - Web2 Click in selector="hgroup > div > div > div > img": Running
9/19/2019 2:42:39 PM - Web2 Click in selector="hgroup > div > div > div > img" : Success
9/19/2019 2:42:39 PM - Web2 Navigation: Running
9/19/2019 2:42:42 PM - Web2 Navigation : Success
9/19/2019 2:42:42 PM - #Regular y esp --> se arrastra imagen hacia otro elemento: Running
9/19/2019 2:42:42 PM - Regular y esp --> se arrastra imagen hacia otro elemento : Success
9/19/2019 2:42:42 PM - Titanium DragAndDrop select "img_00.PNG" and drop in "lista.PNG" Timeout= 20000 Sim= 0.7: Running
9/19/2019 2:42:42 PM - System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.WindowsAzure.Storage.File.CloudFile.DownloadToFile(String path, FileMode mode, AccessCondition accessCondition, FileRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\File\CloudFile.cs:line 540
   at AzureStorage.AzureBot.Download(String fileName, String processId, String userEmail, String runProcessId, String pathOptional) in C:\Users\andres.cruz\source\repos\AutomationPlatform\AzureStorage\AzureBot.cs:line 498
   at TitaniumReader.TitaniumExecute.DragAndDrop(String action) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 357
   at TitaniumReader.TitaniumExecute.SelectAction(String action, Dictionary`2 variables) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 276
   at TitaniumReader.TitaniumExecute.RunLine(String paso, Dictionary`2 variables) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 125
9/19/2019 2:42:42 PM - Titanium DragAndDrop select "img_00.PNG" and drop in "lista.PNG" Timeout= 20000 Sim= 0.7 : Error
9/19/2019 2:42:44 PM - Execution ended

Error.txt
9/19/2019 2:42:44 PM : System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.WindowsAzure.Storage.File.CloudFile.DownloadToFile(String path, FileMode mode, AccessCondition accessCondition, FileRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\File\CloudFile.cs:line 540
   at AzureStorage.AzureBot.Download(String fileName, String processId, String userEmail, String runProcessId, String pathOptional) in C:\Users\andres.cruz\source\repos\AutomationPlatform\AzureStorage\AzureBot.cs:line 498
   at TitaniumReader.TitaniumExecute.DragAndDrop(String action) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 357
   at TitaniumReader.TitaniumExecute.SelectAction(String action, Dictionary`2 variables) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 276
   at TitaniumReader.TitaniumExecute.RunLine(String paso, Dictionary`2 variables) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 125

**Comment by gantonioid** [comment]
Probaste ya sin las comillas en las partes donde le pasas los nombres de las imágenes?
`Titanium DragAndDrop select img_00.PNG and drop in lista.PNG Timeout= 20000 Sim= 0.7`

La documentación no indica las comillas, debe ser por eso el error.
[http://automationplatform.azurewebsites.net/Readers/Tools/Titanium/DragAndDrop](url)

**Comment by julio-soto-0517** [comment]
Buen día, 
también lo he intentado sin las comillas tal como está documentado, sin embargo el log me arroja lo siguiente:
9/19/2019 4:50:06 PM - #Agregar productos a lista de más vendidos: Running
9/19/2019 4:50:06 PM - Agregar productos a lista de más vendidos : Success
9/19/2019 4:50:06 PM - Web2 Click in selector="hgroup > div > div > div > img": Running
9/19/2019 4:50:07 PM - Web2 Click in selector="hgroup > div > div > div > img" : Success
9/19/2019 4:50:07 PM - Web2 Navigation: Running
9/19/2019 4:50:10 PM - Web2 Navigation : Success
9/19/2019 4:50:10 PM - #Regular y esp --> se arrastra imagen hacia otro elemento: Running
9/19/2019 4:50:10 PM - Regular y esp --> se arrastra imagen hacia otro elemento : Success
9/19/2019 4:50:10 PM - Titanium DragAndDrop select img_00.PNG and drop in lista.PNG Timeout= 20000 Sim= 0.7: Running
9/19/2019 4:50:10 PM - Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 722
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 649
   at Microsoft.WindowsAzure.Storage.File.CloudFile.DownloadRangeToStream(Stream target, Nullable`1 offset, Nullable`1 length, AccessCondition accessCondition, FileRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\File\CloudFile.cs:line 1123
   at Microsoft.WindowsAzure.Storage.File.CloudFile.DownloadToStream(Stream target, AccessCondition accessCondition, FileRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\File\CloudFile.cs:line 398
   at Microsoft.WindowsAzure.Storage.File.CloudFile.DownloadToFile(String path, FileMode mode, AccessCondition accessCondition, FileRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\File\CloudFile.cs:line 564
   at AzureStorage.AzureBot.Download(String fileName, String processId, String userEmail, String runProcessId, String pathOptional) in C:\Users\andres.cruz\source\repos\AutomationPlatform\AzureStorage\AzureBot.cs:line 498
   at TitaniumReader.TitaniumExecute.DragAndDrop(String action) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 357
   at TitaniumReader.TitaniumExecute.SelectAction(String action, Dictionary`2 variables) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 276
   at TitaniumReader.TitaniumExecute.RunLine(String paso, Dictionary`2 variables) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 125
Request Information
RequestID:d1909c8e-b01a-000c-4634-6f031f000000
RequestDate:Thu, 19 Sep 2019 21:50:10 GMT
StatusMessage:The specified parent path does not exist.
ErrorCode:ParentNotFound
ErrorMessage:The specified parent path does not exist.
RequestId:d1909c8e-b01a-000c-4634-6f031f000000
Time:2019-09-19T21:50:10.7859320Z

9/19/2019 4:50:10 PM - Titanium DragAndDrop select img_00.PNG and drop in lista.PNG Timeout= 20000 Sim= 0.7 : Error
9/19/2019 4:50:12 PM - Execution ended

Error.txt
9/19/2019 4:50:12 PM : Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 722
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 649
   at Microsoft.WindowsAzure.Storage.File.CloudFile.DownloadRangeToStream(Stream target, Nullable`1 offset, Nullable`1 length, AccessCondition accessCondition, FileRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\File\CloudFile.cs:line 1123
   at Microsoft.WindowsAzure.Storage.File.CloudFile.DownloadToStream(Stream target, AccessCondition accessCondition, FileRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\File\CloudFile.cs:line 398
   at Microsoft.WindowsAzure.Storage.File.CloudFile.DownloadToFile(String path, FileMode mode, AccessCondition accessCondition, FileRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\File\CloudFile.cs:line 564
   at AzureStorage.AzureBot.Download(String fileName, String processId, String userEmail, String runProcessId, String pathOptional) in C:\Users\andres.cruz\source\repos\AutomationPlatform\AzureStorage\AzureBot.cs:line 498
   at TitaniumReader.TitaniumExecute.DragAndDrop(String action) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 357
   at TitaniumReader.TitaniumExecute.SelectAction(String action, Dictionary`2 variables) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 276
   at TitaniumReader.TitaniumExecute.RunLine(String paso, Dictionary`2 variables) in C:\Users\andres.cruz\source\repos\AutomationPlatform\TitaniumReader\TitaniumExecute.cs:line 125
Request Information
RequestID:d1909c8e-b01a-000c-4634-6f031f000000
RequestDate:Thu, 19 Sep 2019 21:50:10 GMT
StatusMessage:The specified parent path does not exist.
ErrorCode:ParentNotFound
ErrorMessage:The specified parent path does not exist.
RequestId:d1909c8e-b01a-000c-4634-6f031f000000
Time:2019-09-19T21:50:10.7859320Z

**Comment by gantonioid** [comment]
Ese otro error es que no encuentra un archivo con ese nombre. Te aseguraste de darle "Upload files" a las imágenes que requieres?
Pásame por favor tu ID de proceso

**Comment by julio-soto-0517** [comment]
Si, de hecho las imágenes fueron cargadas previamente a la ejecución
Process: 1299975559

**Comment by gantonioid** [comment]
Lo solucionamos para tu proceso específico, pero se enviará un update para que no ocurra de nuevo y/o con otros procesos.

**Comment by andresCruzF** [comment]
Hola @julio-soto-0517 , ya se generó y liberó un update a tu usuario , podrías validar su funcionamiento ?

saludos , quedó al pendiente

**Comment by julio-soto-0517** [comment]
Buen día, @andresCruzF , al abrir de nuevo FRIDA para validar con el update, ya no me aparece error, al ejecutar el script, en el log me aparece que ya realizó la acción, sin embargo, al tomar captura de pantalla cuando la ejecución llega a esa parte, la imagen no es arrastrada al lugar que necesito colocarla, ¿podrían asesorarme sobre cómo lograr arrastrar la imagen?

el log me devuelve esto: 
9/23/2019 10:07:22 AM - #Regular y esp --> se arrastra imagen hacia otro elemento: Running
9/23/2019 10:07:22 AM - Regular y esp --> se arrastra imagen hacia otro elemento : Success
9/23/2019 10:07:22 AM - Titanium DragAndDrop select img_00.PNG and drop in lista.PNG Timeout= 20000 sim=0.7: Running
9/23/2019 10:07:23 AM - Titanium DragAndDrop select img_00.PNG and drop in lista.PNG Timeout= 20000 sim=0.7 : Success

¡Saludos!

**Comment by gantonioid** [comment]
@FaustinoLechuga cómo salió esta instrucción en la revisión general?
