### ISSUE TITLE
Error al conectar a BD

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#64]
Esta conexión trabajaba sin problemas y ahorita me empezó a tirar este error

```
15/05/2020 12:33:30 p. m. - DB Connect to DB connectionstring={Server=SRD201050;Initial Catalog=DBSTG;Persist Security Info=False;Integrated Security=True;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;} name={myDB} : Error
15/05/2020 12:33:30 p. m. - Error : Could not load file or assembly 'MySql.Data, Version=8.0.20.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' or one of its dependencies. An attempt was made to load a program with an incorrect format.
15/05/2020 12:33:30 p. m. - Error : System.BadImageFormatException: Could not load file or assembly 'MySql.Data, Version=8.0.20.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'MySql.Data, Version=8.0.20.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' ---> System.BadImageFormatException: Could not load file or assembly '1727514 bytes loaded from TuringExpo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: '1727514 bytes loaded from TuringExpo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: Bad IL format.
   at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, Boolean fSkipIntegrityCheck, SecurityContextSource securityContextSource)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly)
   at Costura.AssemblyLoader.ReadFromEmbeddedResources(Dictionary`2 assemblyNames, Dictionary`2 symbolNames, AssemblyName requestedAssemblyName)
   at Costura.AssemblyLoader.ResolveAssembly(Object sender, ResolveEventArgs e)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
```

**Comment by gantonioid** [comment]
Tuviste update?

**Comment by heber-solis** [comment]
si, tengo la 20200512T0419

**Comment by gantonioid** [comment]
Te puedo mandar una actualización, pero sabes qué tipo de Base de datos es?

El error muestra datos de error en la librería MySQL, pero tu instrucción no lo indica, por lo tanto supongo que si efectivamente es MySQL, se podría corregir el error si lo indicas con type={MY_SQL}
[DB Connect](http://automationplatform.azurewebsites.net/Readers/Tools/DBReader/Connect)

**Comment by heber-solis** [comment]
es SQL SERVER 
esto es lo que estoy usando
`DB Connect to DB connectionstring={Server=SRD201050;Initial Catalog=DBSTG;Persist Security Info=False;Integrated Security=True;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;} name={myDB}`

**Comment by heber-solis** [comment]
este issue ya puede ser cerrado, se solucionó con una update que me mandaron, gracias
